[package]
name = "wiener"
description = "Rendering API for OpenGL and Vulkan"
readme = "README.md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiener_core = { path = "crates/wiener_core", version = "0.1.0" }
wiener_gl = { path = "crates/wiener_gl", version = "0.1.0" }
wiener_utils = { path = "crates/wiener_utils", version = "0.1.0" }
wiener_vk = { path = "crates/wiener_vk", version = "0.1.0" }

[dev-dependencies]
env_logger = "0.10.0"
gl = "0.14.0"
log = "0.4.17"
